services:
  caddy:
    restart: always
    networks:
      - default
      - proxy

  php:
    restart: always
    environment:
      APP_ENV: production
    networks:
      - default
      - proxy

  db:
    restart: always
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
